# Generated by Django 3.2.3 on 2021-06-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210521_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/office-image-placeholder.jpg', null=True, upload_to=''),
        ),
    ]
